[build]
    functions = "functions"

[[redirects]]
    from = '/dashboard/*'
    status = 200
    to = '/dashboard'

[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/:splat"